### ISSUE TITLE
Unable to run with Phoenix

### ISSUE THREAD

**Issue by daveshah** [lpil/mix-test.watch#41]
When grabbing the latest from master, I'm seeing the following:

```
[error] GenServer MixTestWatch.Watcher terminating
** (RuntimeError) cannot begin test transaction with pool Ecto.Pools.Poolboy.
In order to use test transactions with Ecto SQL, you need to
configure your repository to use Ecto.Adapters.SQL.Sandbox:

    pool: Ecto.Adapters.SQL.Sandbox

    (ecto) lib/ecto/adapters/sql.ex:396: Ecto.Adapters.SQL.test_transaction/3
    (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
    (elixir) src/elixir_lexical.erl:16: :elixir_lexical.run/3
    (elixir) src/elixir_compiler.erl:30: :elixir_compiler.quoted/3
    (elixir) lib/code.ex:363: Code.require_file/2
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix) lib/mix/tasks/test.ex:186: Mix.Tasks.Test.run/1
    (mix_test_watch) lib/mix_test_watch/test_task.ex:9: MixTestWatch.TestTask.run/1
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix_test_watch) lib/mix_test_watch/watcher.ex:69: MixTestWatch.Watcher.do_run_tasks/1
    (mix_test_watch) lib/mix_test_watch/watcher.ex:41: MixTestWatch.Watcher.handle_cast/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", :run_tasks}
State: []
```

Running with `{:mix_test_watch, "~> 0.2", only: :dev}` seems to work just fine.

**Comment by lpil** [comment]
Thanks for the report.

**Comment by lpil** [comment]
Is there a repo I can look at?

**Comment by daveshah** [comment]
@lpil absolutely.
I put up a quick example with nothing more than a basic ```mix phoenix.new``` [here](https://github.com/daveshah/watch/tree/master). This works fine as it's deps adds [this](https://github.com/daveshah/watch/blob/master/mix.exs#L39).

I have another branch [here](https://github.com/daveshah/watch/tree/master-mix-test.watch) which doesn't work as it's deps adds the latest [here](https://github.com/daveshah/watch/blob/master-mix-test.watch/mix.exs#L39) 

If you run ```mix deps.get``` then ```mix test.watch``` on each branch, you'll be able to see the issue.

I hope this helps. If you need anything else, just let me know.

Thanks!

**Comment by casio** [comment]
Also running into the issue @daveshah describes.

I guess this is related to ecto 2.0 style sandbox mode when running tests(which is only correctly working in `:test` env, I assume).

Running this works for me(using `master`):
`MIX_ENV=test mix test.watch`

This, however, will cause a complete recompilation of all modules on every change, rendering the whole re-test process rather slow.
@lpil `Code.load_file/1` seemed to work pretty well last I checked(and it was nicely fast, as well). Was there a specific need for explicit compilation?

**Comment by lpil** [comment]
Heya. I'm unsure as to why it's recompiling all the files. It just runs `mix compile

**Comment by lpil** [comment]
Closing this due to inactivity. Please reopen if needed. :)
