### ISSUE TITLE
TokenMissingError

### ISSUE THREAD

**Issue by dotdotdotpaul** [lpil/mix-test.watch#46]
Just added to my mix.exs as directed, ran my tests, then ran with test.watch and I get an exception:

```
$ mix test
.......

Finished in 0.8 seconds
7 tests, 0 failures

Randomized with seed 357360
$ mix test.watch

Running tests...
** (TokenMissingError) nofile:1: missing terminator: ) (for "(" starting at line 1)
    (elixir) lib/code.ex:168: Code.eval_string/3
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:651: Enum.each/2
    (mix) lib/mix/tasks/run.ex:67: Mix.Tasks.Run.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
```

For reference, my mix.lock shows (in case this is version-specific):

```
"mix_test_watch": {:hex, :mix_test_watch, "0.2.6", "9fcc2b1b89d1594c4a8300959c19d50da2f0ff13642c8f681692a6e507f92cab", [:mix], [{:fs, "~> 0.9.1", [hex: :fs, optional: false]}]}
```

Elixir: 1.3.0, MacOS X.

**Comment by adamkittelson** [comment]
A coworker of mine started getting this after we upgraded to Elixir 1.3.0 / Erlang 19.0 as well.

**Comment by dotdotdotpaul** [comment]
I just noticed I could update to Elixir 1.3.1 so I did -- and now it works fine!  Must be something odd with 1.3.0.

**Comment by lpil** [comment]
Yep, there's a bug in 1.3.0 :(
